Ajout d'une gestion des options optimales (script emploi).

diff --git a/bin/emploi_dossier_candidature b/bin/emploi_dossier_candidature
--- a/bin/emploi_dossier_candidature
+++ b/bin/emploi_dossier_candidature
@@ -57,52 +57,97 @@ REGEX_TITRE_LM_ANGLAIS="Resume.*\.${EXTENSION_FICHIER}"
 POSITION_AVANT_COMMANDE="$PWD"
 TYPE_POSTULATION="" # pr gérer les postulation bidons ou les vraies postulations
 
-# Contrôle des arguments :
-SYNTAXE="\nSyntaxe :\n\t$(basename $0)    NOM_DU_POSTE    NOM_DE_LENTREPRISE    [-anglais]\n"
-ARG_FOURNI_TOUS="$*"
-if [[ -z "$1" && -z "$2" ]]
+# Syntaxe
+SYNTAXE="$(syntaxe_afficher_si_erreur "$(basename $0)" "-p NOM_DU_POSTE"  "-e NOM_DE_LENTREPRISE" [--anglais] [--vrai])"
+
+# Note that we use "$@" to let each command-line parameter expand to a
+# separate word. The quotes around "$@" are essential!
+# We need TEMP as the 'eval set --' would nuke the return value of getopt.
+TEMP=$(getopt --options 'e:p:' --longoptions 'anglais,vrai' -q -- "$@")
+# -q : quiet
+# -- : marque la fin des options
+
+# Test si la syntaxe a été correcte (options + arguments)
+if [ $? -ne 0 ]
 then
-    STDERR_afficher_message "\nERREUR : aucun argument fourni."
+    STDERR_afficher_message "ERREUR de syntaxe..."
     STDERR_afficher_message "$SYNTAXE"
     exit 1
-elif [ -z "$2" ]
-then
-    STDERR_afficher_message "\nERREUR : le deuxième argument (nom de l'entreprise) n'a pas été fourni."
-    STDERR_afficher_message "Argument fourni : \"$ARG_FOURNI_TOUS\"."
-    STDERR_afficher_message "$SYNTAXE"
-    exit 2
-else
-    # Définition du nom du poste et de l'entreprise
-    NOM_DU_POSTE="$1"
-    NOM_DE_LENTREPRISE="$2" 
-    shift 2
 fi
 
-# Gestion des autres arguments - autre que nom du poste et nom entreprise
-while [[ $# -gt 0 ]]
-do
+# Contrôle des arguments
+FLAG_OPTION_E=
+FLAG_OPTION_P=
+
+# Remise des options en paramètres positionnels
+eval set -- "$TEMP"
+unset TEMP
+
+while true; do
     case "$1" in
-    -anglais )      # Parmétrisation de la recherche en anglais ici
-                    TITRE_CV="$TITRE_CV_ANGLAIS"
-                    TITRE_LM="$TITRE_LM_ANGLAIS"
-                    TITRE_CERTIFICATS_DE_TRAVAIL="$TITRE_CERTIFICATS_DE_TRAVAIL_ANGLAIS"
-                    TITRE_DIPLOMES="$TITRE_DIPLOMES_ANGLAIS"
-                    REGEX_TITRE_CV="$REGEX_TITRE_CV_ANGLAIS"
-                    REGEX_TITRE_LM="$REGEX_TITRE_LM_ANGLAIS"
-                    FIN_DU_REPERTOIRE_CANDIDATURE_VERSION_ANGLAISE="_EN"
-                    shift 1
-                    ;; 
-    -vrai )         REPERTOIRE_DE_BASE="${REPERTOIRE_GENERAL_RECHERCHE_EMPLOI}/${REPERTOIRE_RECHERCHE_NON_CHOMAGE}"
-                    FLAG_POSTULATION_CHOMAGE="false"
-                    shift 1
-                    ;;
-    * )             STDERR_afficher_message "\nERREUR : l'argument fourni \"$1\" est invalide."
-                    STDERR_afficher_message "Tous les arguments fournis : \"$ARG_FOURNI_TOUS\"."
-                    STDERR_afficher_message "$SYNTAXE"
-                    exit 3
-                    ;;
-    esac
+	-e )  
+	    FLAG_OPTION_E=1
+            NOM_DE_LENTREPRISE="$2"
+            shift 2
+            continue
+            ;;
+	-p )
+	    FLAG_OPTION_P=1
+            NOM_DU_POSTE="$2"
+            shift 2
+            continue
+       	    ;;
+	--anglais )
+	    # Parmétrisation de la recherche en anglais ici
+            TITRE_CV="$TITRE_CV_ANGLAIS"
+            TITRE_LM="$TITRE_LM_ANGLAIS"
+            TITRE_CERTIFICATS_DE_TRAVAIL="$TITRE_CERTIFICATS_DE_TRAVAIL_ANGLAIS"
+            TITRE_DIPLOMES="$TITRE_DIPLOMES_ANGLAIS"
+            REGEX_TITRE_CV="$REGEX_TITRE_CV_ANGLAIS"
+            REGEX_TITRE_LM="$REGEX_TITRE_LM_ANGLAIS"
+            FIN_DU_REPERTOIRE_CANDIDATURE_VERSION_ANGLAISE="_EN"
+            shift 1
+            ;; 
+	--vrai )
+            REPERTOIRE_DE_BASE="${REPERTOIRE_GENERAL_RECHERCHE_EMPLOI}/${REPERTOIRE_RECHERCHE_NON_CHOMAGE}"
+            FLAG_POSTULATION_CHOMAGE="false"
+            shift 1
+            ;;
+       	'--')
+	    shift
+	    break
+      	    ;;
+        * )
+	    # Gestion des erreurs pour tout autre bug
+            STDERR_afficher_message "ERREUR interne\n"
+            STDERR_afficher_message "$SYNTAXE"
+            exit 2
+            ;;
+	esac
 done
+
+# Test si les options requises ont été fournies (=test si flag défini)
+if [ ! -z "$FLAG_OPTION_E" ] && [ ! -z "$FLAG_OPTION_P" ]
+then
+    # Test si d'autres darguments = en trop (=test si $1 défini)
+    if [ ! -z "$1" ]
+    then
+        STDERR_afficher_message "\nERREUR : argument(s) en trop : \"$*\".\n"
+        STDERR_afficher_message "$SYNTAXE"
+        exit 3
+    else
+        :
+    fi
+else
+    STDERR_afficher_message "\nERREUR : Vous devez fournir toutes les options requises.\n"
+    STDERR_afficher_message "$SYNTAXE"
+    exit 4
+fi
+
+########## FIN GESTION ARGUMENTS/OPTIONS ####################
+
+
+
 
 # Contrôle si disque dur connecté (=si le répertoire existe) - quitte sinon
 if [ -d "$REPERTOIRE_GENERAL_RECHERCHE_EMPLOI" ]
@@ -110,11 +155,11 @@ then
     :
 else
     STDERR_afficher_message "\nERREUR : le répertoire :\n\"$REPERTOIRE_GENERAL_RECHERCHE_EMPLOI\"\nn'est pas existant.\nIl est possible que le disque dur ne soit pas connecté.\n"
-    exit 4
+    exit 5
 fi
 
 # Ouverture du tableau recherche emploi
-fichier_ouvrir -f "$TABLEAU_RECHERCHE_EMPLOI" || exit 4
+fichier_ouvrir -f "$TABLEAU_RECHERCHE_EMPLOI" || exit 6
 
 # Obtention de la date
 DATE_AJD="$(date -I)"
