Debug the script, add option to silent the daemon (STDOUT and STDERR to /dev/null), add management of command containing several 'words' (example 'echo This is a dummy echo n', add error check while executing daemon and if error occurs, print error message to STDERR with the error code of the command. Tested sucessfully in several test cases so ready for production !

diff --git a/guix/daemonize b/guix/daemonize
--- a/guix/daemonize
+++ b/guix/daemonize
@@ -1,14 +1,5 @@
 #!/usr/bin/env bash
 
-: <<"TODOLIST"
-DEBUG THE ISSUE WITH PASSING OPTION WITH OPTION NAME '-S SLEEPTIME'
-
-OPTION SEND TO /DEV/NULL
-CHECK THAT THE FORK AND REFORK WORKS - PRINT ERROR MESSAGE ELSE
-ADAPT EXIT CODE NUMBER
-
-TODOLIST
-
 # Theory reminder regarding the commands :
 # 'fork' :
 #     The Fork system call is used for creating a new process in Linux, and Unix systems, which is called the child process, which runs concurrently with the process that makes the fork() call (parent process). After a new child process is created, both processes will execute the next instruction following the fork() system call.
@@ -19,7 +10,7 @@ source functions_personal
 
 # Syntax
 SYNTAX="$(syntaxe_afficher_si_erreur "$(basename $0)" "-c COMMAND_TO_DAEMONIZE" "[-d DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR]" "[-s SLEEP_TIME_FOR_DAEMON]" "[--silent]")"
-# -c COMMAND_TO_DAEMONIZE
+# -c COMMAND_TO_DAEMONIZE : if it contains several arguments, the whole command has to be within single quotes.
 # -d DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR : the directory to write the daemon STDOUT and STDERR. It has to be a directory were the all users can write files - else the daemon will not have enough rights to do so.
 # -s SLEEP_TIME_FOR_DAEMON : the sleep time between each daemon loop to wait before executing a recurrent command. If not provided, the command will be executed only once.
 # --silent : send STDOUT and STDERR to /dev/null.
@@ -37,15 +28,6 @@ DEFAULT_DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR="/tmp"
 DEFAULT_STDOUT_FILE_BASENAME="$(basename $0)_stdout"
 DEFAULT_STDERR_FILE_BASENAME="$(basename $0)_stderr"
 
-
-
-# Debug variable to be removed after development
-DEBUG_FILE="/tmp/debug-file-daemonize"
-echo "DEBUG ARGUMENT $(basename $0) $@" >> $DEBUG_FILE
-
-
-
-
 ##################################################################
 ############### BEGINNING OF OPTION MANAGEMENT ###################
 ##################################################################
@@ -57,8 +39,6 @@ TEMP=$(getopt --options 'a:c:d:s:t:' --longoptions 'silent' -q -- "$@")
 # -q : quiet
 # -- : to explicitly show the options end
 
-echo "DEBUG BEFORE OPTION PROCESSING" >> $DEBUG_FILE
-
 # Test whether syntax was correct (options + arguments)
 if [ $? -ne 0 ]
 then
@@ -66,8 +46,6 @@ then
     STDERR_show_message "$SYNTAX"
     exit 1
 fi
-
-echo "DEBUG AFTER SYNTAX CHECK" >> $DEBUG_FILE
 
 # Arguments check
 FLAG_OPTION_A=
@@ -97,7 +75,7 @@ while true; do
 		*)
 		    STDERR_show_message "\nERROR : the provided argument to '-a' = \"$ACTION_TO_PROCESS\" is not a correct one. You should NOT provide such option.\n"
 		    STDERR_show_message "$SYNTAX"
-                    exit 1 
+                    exit 2 
 	       ;;
 	    esac
             continue
@@ -120,7 +98,7 @@ while true; do
 	    else
 		STDERR_show_message "\nERROR : the provided argument to '-d' = \"$DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR\" is not a directory.\n"
 		STDERR_show_message "$SYNTAX"
-                exit 1 
+                exit 3 
 	    fi
 	    continue
             ;;
@@ -141,18 +119,18 @@ while true; do
 		else
 		    STDERR_show_message "\nERROR : the provided argument to '-s' = \"$SLEEP_TIME_FOR_DAEMON\" should be greater or equal to 1.\n"
 		    STDERR_show_message "$SYNTAX"
-                    exit 1 
+                    exit 4 
 		fi
 	    else
 		STDERR_show_message "\nERROR : the provided argument to '-s' = \"$SLEEP_TIME_FOR_DAEMON\" is not an positive int number.\n"
 		STDERR_show_message "$SYNTAX"
-		exit 1 
+		exit 5 
 	    fi
             continue
             ;;
-	--silent)
+	--silent )
 	    FLAG_OPTION_SILENT=1
-	    shift 2
+	    shift
 	    # Set the option to be passed to future 'eval' commands
             OPTION_SILENT="--silent"
             continue
@@ -166,23 +144,21 @@ while true; do
 	    shift
 	    break
       	    ;;
-        * )
+        * )	    
 	    # Error management for all other bugs
             STDERR_show_message "ERROR: internal error...\n"
             STDERR_show_message "$SYNTAX"
-            exit 2
+            exit 6
             ;;
 	esac
 done
-
-echo "DEBUG 176 AFTER OPTION PROCESSING" >> $DEBUG_FILE
 
 # Test whether other arguments were provided = in excess (=test if $1 is defined)
 if [ ! -z "$1" ]
 then
     STDERR_show_message "\nERROR : argument(s) in excess : \"$*\".\n"
     STDERR_show_message "$SYNTAX"
-    exit 3
+    exit 7
 fi
 
 # Test if the requested option(s) were provided
@@ -190,7 +166,7 @@ if [ -z "$FLAG_OPTION_C" ]
 then
     STDERR_show_message "\nERROR : Please provide all requested argument(s).\n"
     STDERR_show_message "$SYNTAX"
-    exit 3
+    exit 8
 fi
 
 
@@ -224,8 +200,6 @@ else
     STDERR_FILE_BASENAME="$DEFAULT_STDERR_FILE_BASENAME"
 fi
 
-echo "DEBUG 225 END OF OPTION PROCESSING" >> $DEBUG_FILE
-
 ##################################################################
 ############### MAIN SCRIPT CODE #################################
 ##################################################################
@@ -244,14 +218,15 @@ cd /
 ##################################################################
 
 if [ "$ACTION_TO_PROCESS" = "fork" ]
-then
-    echo -e "\nDEBUG fork 222\n" >> $DEBUG_FILE 
+then 
     # Execute the command in a new session
     # Here : execute this script by passing some arguments in a background process
     # setsid runs a program in a new session.
     # The command calls 'fork' if already a process group leader.
     # The argument "child" is used by the block code above
-    eval setsid $SCRIPT_DIRECTORY/$SCRIPT_BASENAME -a "refork" -c "${COMMAND_TO_DAEMONIZE@Q}" -d "$DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR" -t "$TTY_TO_USE" "$OPTION_SLEEP_TIME" "$OPTION_SILENT" &
+    # The 'eval' command is required because of some options provided in two parts but within one variable.
+    # Example the sleep time can be forwarded from the first call to the fork through a variable '-s SLEEP_TIME_FOR_DAEMON' containing two elements.
+    eval setsid "${SCRIPT_DIRECTORY}/${SCRIPT_BASENAME}" -a "refork" -c "${COMMAND_TO_DAEMONIZE@Q}" -d "$DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR" -t "$TTY_TO_USE" "$OPTION_SLEEP_TIME" "$OPTION_SILENT" &
     # End this command (after having created a child above)
     exit 0
     
@@ -267,11 +242,10 @@ then
     # The argument "reforking_the_daemon" is used by the block code below
     # Recall this script and close STDIN + silent mode + background process
     # Here : reforks
-    $SCRIPT_DIRECTORY/$SCRIPT_BASENAME -a "daemon"  -c "${COMMAND_TO_DAEMONIZE@Q}" -d "$DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR" -t "$TTY_TO_USE" "$OPTION_SLEEP_TIME" "$OPTION_SILENT" </dev/null >/dev/null 2>/dev/null &
-    fi
-
-    echo -e "\nDEBUG END OF refork 240\n" >> $DEBUG_FILE 
-
+    # The 'eval' command is required because of some options provided in two parts but within one variable.
+    # Example the sleep time can be forwarded from the first call to the fork through a variable '-s SLEEP_TIME_FOR_DAEMON' containing two elements.
+    eval "${SCRIPT_DIRECTORY}/${SCRIPT_BASENAME}" -a "daemon"  -c "${COMMAND_TO_DAEMONIZE@Q}" -d "$DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR" -t "$TTY_TO_USE" "$OPTION_SLEEP_TIME" "$OPTION_SILENT" </dev/null >/dev/null 2>/dev/null &
+ 
     # End this command (after forking : having recalled the script in a new process)    
     exit 0
 
@@ -281,20 +255,17 @@ then
 
 elif [ "$ACTION_TO_PROCESS" = "daemon" ]
 then
-
-    echo -e "\nDEBUG daemon 261\n" >> $DEBUG_FILE
-    
     # Set the path of stdout and stderr files
     STDOUT_FILE_FOR_DAEMON="${DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR}/${STDOUT_FILE_BASENAME}"
     STDERR_FILE_FOR_DAEMON="${DIRECTORY_FOR_DAEMON_STDOUT_AND_STDERR}/${STDERR_FILE_BASENAME}"
-
+    
     # Set STDOUT, STDERR and close STDIN
     # exec without arguments : If command is not specified, any redirections take effect in the current shell, and  the  return status  is 0.
     exec >"$STDOUT_FILE_FOR_DAEMON"
     exec 2>"$STDERR_FILE_FOR_DAEMON"
     exec 0</dev/null
     
-    # Empty the STDIN and STDOUT file at each run of the script
+    # Empty the STDIN and STDOUT file at each run of the script (at each daemon launching)
     cp /dev/null "$STDOUT_FILE_FOR_DAEMON"
     cp /dev/null "$STDERR_FILE_FOR_DAEMON"
     
@@ -302,15 +273,25 @@ then
     if [ ! -z "$FLAG_OPTION_S" ]
     then
 	# If so, infinite loop that execute the command and then sleeps X seconds
-	{ while true
-	  do
-	      $COMMAND_TO_DAEMONIZE
-	      sleep $SLEEP_TIME_FOR_DAEMON
-	  done
-	}
+	while true
+	do	    
+            { eval $COMMAND_TO_DAEMONIZE &&
+		  sleep $SLEEP_TIME_FOR_DAEMON
+	    } ||
+	    # If error occurs, error message to STDERR + exit with error.
+	    { echo -e "\nERROR : the command '$COMMAND_TO_DAEMONIZE' exited with error code $?.\n"
+		exit 9
+	    } >&2
+	done
     else
-    	# Else, execute the command once
-        $COMMAND_TO_DAEMONIZE
+    	# Else, execute the command once - with error check
+        { eval $COMMAND_TO_DAEMONIZE &&
+	  exit 0
+	} ||
+	# If error occurs, error message to STDERR + exit with error.
+	{ echo -e "\nERROR : the command '$COMMAND_TO_DAEMONIZE' exited with error code $?.\n"
+	  exit 10
+	} >&2
     fi
 fi
 
