Added several enhancement : options management, if no dir was provided by the user, propose only between the dirs that needed to be pushed. If a dir was provided, check if it is a relative or absolute path, if it exists and it it is a git repo dir - exit else / also show files to be committed before requested a user message to add with the commit if this later was not provided as a script argument. Sucessfully tested - ready and pushed to production.

diff --git a/guix/git_commit_avec_message b/guix/git_commit_avec_message
--- a/guix/git_commit_avec_message
+++ b/guix/git_commit_avec_message
@@ -1,97 +1,181 @@
 #!/usr/bin/env bash
 
-# Syntaxe :
-# $1 : REPERTOIRE_PARMI_LES_REPERTOIRES_GIT_SANS_LE_PATH_COMPLET (optionnel)
-# $2 : MESSAGE_AVEC_LE_GIT_PUSH (optionnel)
-
 source fonctions_personnelles
 
-CHOIX="" # besoin de ce paramètre plus tard pour le message d'affichage final.
+# Syntaxe :
+SYNTAXE="$(syntaxe_afficher_si_erreur "$(basename $0)" "[-r GIT_REPO_TO_PUSH]" "[-m MESSAGE_WITH_COMMIT]")"
 
-# Contrôle des arguments
-SYNTAXE="$(syntaxe_afficher_si_erreur "$(basename $0)" "[REPERTOIRE_PARMI_LES_REPERTOIRES_GIT_SANS_LE_PATH_COMPLET]" "[MESSAGE_AVEC_LE_GIT_PUSH]")"
-if [ -z "$1" ] # si aucun argument n'est fourni avec la commande, je demande le nom du dossier à push.
+####### BEGINNING OF OPTION MANAGEMENT ##########
+
+# Note that we use "$@" to let each command-line parameter expand to a
+# separate word. The quotes around "$@" are essential!
+# We need TEMP as the 'eval set --' would nuke the return value of getopt.
+TEMP=$(getopt --options 'r:m:' -q -- "$@")
+# -q : quiet
+# -- : to explicitly show the options end
+
+# Test whether syntax was correct (options + arguments)
+if [ $? -ne 0 ]
 then
-    # Obtention de la liste des répertoires git potentiellement pushables
-    declare -a LISTE_REPERTOIRES_GIT
-    OPTION_SORTIE="Annuler le git push"
-    for repertoire in $REPERTOIRE_DEVELOPPEMENT/*
-    do
-        repertoire=${repertoire##*/} # suppression de tout le path sauf la dernière partie
-        LISTE_REPERTOIRES_GIT+=("$repertoire")
-    done
-    LISTE_REPERTOIRES_GIT+=("$OPTION_SORTIE") # ajout de l'option de sortie en fin de liste
-    DERNIERE_OPTION=${#LISTE_REPERTOIRES_GIT[@]}
+    STDERR_afficher_message "ERROR: syntax..."
+    STDERR_afficher_message "$SYNTAXE"
+    exit 1
+fi
 
-    # Sélection du répertoire à push au sein du répertoire de développement
-    until [ -n "$CHOIX" ] # Boucler tant que le choix n'est pas correct = tant que choix n'est pas un string > 1char
-    do
-        echo -e "\nChoisissez le répertoire git à push :\n"
-        select CHOIX in "${LISTE_REPERTOIRES_GIT[@]}"
-        do
-            echo "$CHOIX"
-            break 
-        done
-        if [ -n "$CHOIX" ]
-        then
-            if [ "$CHOIX" != "$OPTION_SORTIE" ]
-            then
-                echo -e "\nVous avez choisi de push le répertoire git \"$CHOIX\".\n"
-                REPERTOIRE_GIT_A_PUSH="$REPERTOIRE_DEVELOPPEMENT/$CHOIX"
-            else
-                echo -e "\nVous avez choisi d'annuler le git push.\n"
-                exit 0
-            fi
-        else
-            echo -e "ERREUR : votre saisie ne fait pas partie de la liste de choix.\nTapez \"$DERNIERE_OPTION\" pour \"$OPTION_SORTIE\""
-        fi
-    done
-else
-    REPERTOIRE_PARMI_LES_REPERTOIRES_GIT_SANS_LE_PATH_COMPLET="$1"
-    CHOIX="$REPERTOIRE_PARMI_LES_REPERTOIRES_GIT_SANS_LE_PATH_COMPLET" # Pour le message final uniquement
-    REPERTOIRE_GIT_A_PUSH="$REPERTOIRE_DEVELOPPEMENT/${REPERTOIRE_PARMI_LES_REPERTOIRES_GIT_SANS_LE_PATH_COMPLET}"
-    if [ -d "$REPERTOIRE_GIT_A_PUSH" ]
+# Arguments check
+FLAG_OPTION_M=
+FLAG_OPTION_R=
+
+# Re-set options through positional parameters
+eval set -- "$TEMP"
+unset TEMP
+
+while true; do
+    case "$1" in
+	-m )  
+	    FLAG_OPTION_M=1
+            MESSAGE_WITH_COMMIT="$2"
+            shift 2
+            continue
+            ;;
+	-r )  
+	    FLAG_OPTION_R=1
+            GIT_REPO_TO_PUSH="$2"
+            shift 2
+            continue
+            ;;
+       	'--')
+	    shift
+	    break
+      	    ;;
+        * )
+	    # Error management for all other bugs
+            STDERR_afficher_message "ERROR: internal error...\n"
+            STDERR_afficher_message "$SYNTAXE"
+            exit 2
+            ;;
+	esac
+done
+
+# Test whether other arguments were provided = in excess (=test if $1 is defined)
+if [ ! -z "$1" ]
+then
+    STDERR_afficher_message "\nERROR : argument(s) in excess : \"$*\".\n"
+    STDERR_afficher_message "$SYNTAXE"
+    exit 3
+fi
+    
+# The below parameter is needed later for each 'if' cases so has to be set here.
+CHOICE_GIT_REPO_TO_PUSH=""
+
+# Test if git repo was provided as script argument
+if [ ! -z "$FLAG_OPTION_R" ]
+then
+    # Check if the file provided is a directory and if it is a git repo
+    CHOICE_GIT_REPO_TO_PUSH="$GIT_REPO_TO_PUSH"
+    # If the argument provided is not a dir
+    if [ ! -d "$CHOICE_GIT_REPO_TO_PUSH" ]
     then
-        :
+	# Check if it is the basename of a dir within the git repos dir
+	if [ ! -d "${REPERTOIRE_DEVELOPPEMENT}/${CHOICE_GIT_REPO_TO_PUSH}" ]
+	then
+	    # Exit with error if the later is not a dir within the git repos dir
+	    STDERR_afficher_message "\nERROR : the argument provided for '-r' : \"$CHOICE_GIT_REPO_TO_PUSH\" is not a directory.\n"
+            STDERR_afficher_message "$SYNTAXE"
+	    exit 4
+	else
+	    # Else adapt the path
+	    CHOICE_GIT_REPO_TO_PUSH="${REPERTOIRE_DEVELOPPEMENT}/${CHOICE_GIT_REPO_TO_PUSH}"
+	fi
     else
-        echo -e "\nERREUR : le premier argument :\n\"$REPERTOIRE_PARMI_LES_REPERTOIRES_GIT_SANS_LE_PATH_COMPLET\"\nn'est pas un répertoire ou ne fait pas partie du répertoire \"developpement\" personnel."
-        echo -e "$SYNTAXE"
-        exit 1
+	# Else, check that it is a dir within the git repo dir
+	# This avoids to control if it is a git dir because I only use this dir for this usage.
+	if [[ "$CHOICE_GIT_REPO_TO_PUSH" =~ ^"$REPERTOIRE_DEVELOPPEMENT".*$ ]]
+	then
+	    :
+	else
+	    # Exit with error if the later is not a dir within the git repos dir
+	    STDERR_afficher_message "\nERROR : the argument provided for '-r' : \"$CHOICE_GIT_REPO_TO_PUSH\" is not a git directory located within the dir REPERTOIRE_DEVELOPPEMENT = \"$REPERTOIRE_DEVELOPPEMENT\".\n"
+	    STDERR_afficher_message "$SYNTAXE"
+	    exit 5
+	fi	
+    fi
+else
+    # Else, ask for it.
+    # Fill an array with all names of git repos that require to push
+    declare -a ARRAY_OF_REPO_TO_GIT_PUSH
+    while read GIT_REPO_NEEDING_TO_BE_PUSHED
+    do
+	ARRAY_OF_REPO_TO_GIT_PUSH+=("$GIT_REPO_NEEDING_TO_BE_PUSHED")
+    done < <(echo $(git_check_if_up_to_date) |
+	sed -E "s/[[:space:]][0-9]*[[:space:]]*[-][[:space:]]/\\n/g" | tail -n +2)
+
+    # If array is empty, exit with sucess code
+    if [ ${#ARRAY_OF_REPO_TO_GIT_PUSH[@]} -eq 0 ]
+    then
+	echo -e "\nThe script ${0##*/} cannot commit any repo because they are all already up-to-date.\n"
+	exit 0
+    fi
+    
+    # Choose which repo to push
+    OPTION_TO_STOP="Quit"
+    QUESTION_WHICH_REPO_TO_PUSH="Which git repo would you like to push ? "
+    select_parmi_liste ARRAY_OF_REPO_TO_GIT_PUSH CHOICE_GIT_REPO_TO_PUSH "$QUESTION_WHICH_REPO_TO_PUSH" "$OPTION_TO_STOP"
+
+    # Show confirmation message of the action choosed
+    if [ "$CHOICE_GIT_REPO_TO_PUSH" != "$OPTION_TO_STOP" ]
+    then
+	echo -e "\nYou choosed to git push the git repo : \"$CHOICE_GIT_REPO_TO_PUSH\".\n"
+	# Set the path of the git repo to be pushed
+	CHOICE_GIT_REPO_TO_PUSH="$REPERTOIRE_DEVELOPPEMENT/$CHOICE_GIT_REPO_TO_PUSH"
+    else
+	echo -e "\nYou choosed to cancel the git push.\n"
+	exit 0
     fi
 fi
 
-# Aller dans le répertoire fourni
-cd $REPERTOIRE_GIT_A_PUSH
 
-# Spécificité avec le répertoire Bash avec Git qui ne push pas le script car il le run.
-if [ $PWD == "$REPERTOIRE_DEVELOPPEMENT/bash" ] # Uniquement pour mon répertoire Git Bash
+
+########## END OF OPTION MANAGEMENT ####################
+
+# Go into the git repo to push
+cd $CHOICE_GIT_REPO_TO_PUSH
+
+# SPECIAL : only if the git repo to be pushed is bash
+if [ $PWD == "$REPERTOIRE_DEVELOPPEMENT/bash" ]
 then
-    git add "$0" # comme je run ce fichier "$0" il semblerait que Git ne le prenne pas d'office.
-    #DEBUG echo "Rép bash" # DEBUG
-else
-    :
+    # Add this script too because if seems that git does not push it because it is currently runned.
+    git add "$0"
 fi
 
-# Push du git
-{   git add . &&
-    git status &&
-    MESSAGE_AVEC_LE_GIT_PUSH="$2" &&
-    while [ ${#MESSAGE_AVEC_LE_GIT_PUSH} -eq 0 ]
+# Add all files to commit
+git add . &&
+
+# Show the files that will be pushed
+git status &&
+
+# If no message with the commit were provided as script argument, ask it.
+{ if [ -z "$FLAG_OPTION_M" ]
+then
+    while [ ${#MESSAGE_WITH_COMMIT} -eq 0 ]
     do
-        read -rp "Quelle message voudriez-vous joindre avec le push ? " MESSAGE_AVEC_LE_GIT_PUSH
-        # -r : ne permet pas au barre oblique de se comporter comme des char spéciaux
-        if [ ${#MESSAGE_AVEC_LE_GIT_PUSH} -eq 0 ]
-        then
-            echo -e "\nERREUR : Veuillez saisir un message d'au moins 1 char.\n"
-        fi
-    done &&
-    git commit -m "$MESSAGE_AVEC_LE_GIT_PUSH" &&
-    git push  && echo -e "\nCommit du répertoire \"$CHOIX\" = OK\n" &&
+	read -rp "Which message to add with the git push ? " MESSAGE_WITH_COMMIT
+	# -r : do not let the slashes '\' to behave like special char
+	if [ ${#MESSAGE_WITH_COMMIT} -eq 0 ]
+	then
+	    STDERR_afficher_message "\nERROR : At least one char have to be written for the 'git commit' message.\n"
+	fi
+    done
+fi } &&
+
+# Git commit and push with success/failure confirmation
+{   git commit -m "$MESSAGE_WITH_COMMIT" &&
+    git push  && echo -e "\nCommit of git repo \"$CHOICE_GIT_REPO_TO_PUSH\" = DONE\n" &&
     cd "$OLDPWD" &&
     exit 0
 } ||
-{ echo -e "\nLe commit du répertoire \"$CHOIX\" n'a pas pu être correctement fait OU il n'y avait rien à push."
+{ STDERR_afficher_message "\nERROR : The commit of the git repo \"$CHOICE_GIT_REPO_TO_PUSH\" failed or there was nothing to push.\n"
   cd "$OLDPWD"
-  exit 1
+  exit 6
 }
 
